#**************************************************
#* Copyright 2019, MapleLabs, All Rights Reserved.
#*
#**************************************************
---

#- name: copy install-agent.py to /tmp
#  copy:
#     src: files/install-agent.py
#     dest: /tmp

- debug:
    msg: python /tmp/agent-installer-apm/install-agent.py -pi '{{ agent_args | to_json(indent=0) | regex_replace('\n','') }}'
  when: agent_args is defined

- name: Execute install-agent.py with argument
  command: python /tmp/agent-installer-apm/install-agent.py -pi '{{ agent_args | to_json(indent=0) | regex_replace('\n','') }}'
  when: agent_args is defined

- name: Execute install-agent.py without argument
  command: python /tmp/agent-installer-apm/install-agent.py
  when: agent_args is not defined